#!/bin/sh

# source xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

#dwm restart loop
while :; do
	ssh-agent dwm
done
#exec bspwm
