import = [
      # "~/.config/alacritty/catppuccin-mocha.toml"
      "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11
offset.y = 4  # For line spacing (default: 0)

[font.bold]
family = "Jet Brains Mono"
style = "Bold"

[font.bold_italic]
family = "Jet Brains Mono"
style = "Bold Italic"

[font.italic]
family = "Jet Brains Mono"
style = "Italic"

[font.normal]
family = "Jet Brains Mono"
style = "Regular"

[scrolling]
history = 5000

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 1

[window.position]
x = 0
y = 0

# BEGIN ACE
[colors.bright]
black = "#939a95"
blue = "#818F7D"
cyan = "#99A99D"
green = "#68766E"
magenta = "#7D8C82"
red = "#57675F"
white = "#d2dcd6"
yellow = "#76847A"

[colors.cursor]
cursor = "#d2dcd6"
text = "#090f0f"

[colors.normal]
black = "#090f0f"
blue = "#818F7D"
cyan = "#99A99D"
green = "#68766E"
magenta = "#7D8C82"
red = "#57675F"
white = "#d2dcd6"
yellow = "#76847A"

[colors.primary]
background = "0x282828"
foreground = "#d2dcd6"
# END ACE

