" Install plug.vim automatically
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin('~/.vim/plugged')
	Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
	Plug 'morhetz/gruvbox' 	" gruvbox colorscheme
	Plug 'christoomey/vim-tmux-navigator' 	" vim tmux navigator
	Plug 'justinmk/vim-sneak' 	" vim sneak
	Plug 'unblevable/quick-scope' " quick scope
	Plug 'raimondi/delimitmate' " auto closing brackets/quotes/...
	Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
	Plug 'tpope/vim-commentary'
	"Plug 'ctrlpvim/ctrlp.vim'
	Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
	Plug 'junegunn/fzf.vim'
	Plug 'preservim/nerdtree' |
            \ Plug 'Xuyuanp/nerdtree-git-plugin'
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

"Leader Key
let mapleader="\<Space>"

" start from where you left before
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" set $RC to access vimrc file within vim
	let $RC="$HOME/.vim/vimrc"

" color column indicating max char in a line for c files
	autocmd BufNewFile,BufRead *.c set colorcolumn=80
	autocmd BufNewFile,BufRead *.h set colorcolumn=80
	autocmd BufNewFile,BufRead *.rst set colorcolumn=80

" set line number and relative line numbers
	set number relativenumber

" No statusbar
	set laststatus=0

" system clipboard
	set clipboard=unnamed

" Search for tags file
	set tags=tags;/
" show trailing white spaces and tabs
	set listchars=tab:_\ ,trail:_
	" show/hide trailing spaces and tabs
	function! ListToggle()
		:set list!
	endfunction
	nnoremap tl :call ListToggle()<CR>

" Enable auto-completion
	set wildmenu
	set wildmode=longest,list,full

" syntax coloring 
	syntax on
	set background=dark
	colorscheme gruvbox

" set tabstop to 4 and shiftwidth to 4
	set tabstop=4 shiftwidth=4

" indentation
	set autoindent smartindent cindent

" Search settings
	set incsearch
	set ignorecase

" no text wrap
	set nowrap

" mouse enable
	" set mouse=a

" show command at the bottom right of the screen
	set showcmd

" split panes to right and below
	set splitright splitbelow

" Windows navigation
	nnoremap <C-j> <C-w>j
	nnoremap <C-k> <C-w>k
	nnoremap <C-l> <C-w>l
	nnoremap <C-h> <C-w>h
	nnoremap <C-f> <C-w>F<C-w>L

" terminal in vertical mode
	command! Vterm :vert term 

" Extras
	inoremap jj <ESC>
	inoremap JJ <ESC>
	nnoremap ; :

" Generate tags file from within vim 
	function! MakeTags()
		:!ctags -R . && echo "tags generated"
	endfunction

	nnoremap mt :call MakeTags()<CR>

" Presentation mode
	function SetvimPresentation()
		set nonu
		set nornu
		nnoremap <buffer> <Right> :n<CR>
		nnoremap <buffer> <Left> :N<CR>
		nnoremap <buffer> <space>l :n<CR>
		nnoremap <buffer> <space>h :N<CR>
	endfunction

"	autocmd BufNewFile,BufRead *.md call SetvimPresentation()
	nnoremap <F5> :call SetvimPresentation()<CR>

" tmux navigator
	let g:tmux_navigator_no_mappings = 1

	nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
	nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
	nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
	nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
	nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>

" arrow keys to resize panes in normal mode
	nnoremap <left> <Esc><C-w><<Insert>
	nnoremap <right> <Esc><C-w>><Insert>
	nnoremap <up> <Esc><C-w>+<Insert>
	nnoremap <down> <Esc><C-w>-<Insert>

" you better use the vim keys
	inoremap <left> <nop>
	inoremap <right> <nop>
	inoremap <up> <nop>
	inoremap <down> <nop>

" move by line on screen
	nnoremap j gj
	nnoremap k gk

" move faster
	nnoremap <S-k> 5k
	nnoremap <S-j> 5j


" quickscope
	augroup qs_colors
		autocmd!
		autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
		autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
	augroup END

" transparent background
	hi Normal guibg=NONE ctermbg=NONE

" hex code colors
	set termguicolors
	let g:Hexokinase_highlighters = ['backgroundfull']

" highlight current line
	set cursorline

" nerd git config
let g:NERDTreeGitStatusShowClean = 1 " default: 0
let g:NERDTreeGitStatusConcealBrackets = 1 " default: 0

" NERDTree
nnoremap <leader>e :NERDTreeToggle<CR>
" show hidden files by default
let NERDTreeShowHidden=1
" Open nerdtree window on opening Vim if no file is specified
autocmd VimEnter * if argc() == 0 | NERDTree | wincmd p | endif

" Refresh the current folder if any changes
autocmd BufEnter NERD_tree_* | execute 'normal R'
au CursorHold * if exists("t:NerdTreeBufName") | call <SNR>15_refreshRoot() | endif

"Reload the window if directory is changed
augroup DIRCHANGE
    au!
    autocmd DirChanged global :NERDTreeCWD
augroup END

"Close nerdtree automatically if it is theonly window open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

vnoremap < <gv
vnoremap > >gv

" Terminal remaps

set t_Co=256
set t_AB=^[[48;5;%dm
set t_AF=^[[38;5;%dm
nnoremap <silent> <Leader>t :term ++rows=9 ++close<cr>
tnoremap ; :
tnoremap : ;
" navigation between terminals and other panes
tmap <silent> <C-j> <C-w>j
tmap <silent> <C-k> <C-w>k
tmap <silent> <C-l> <C-w>l
tmap <silent> <C-h> <C-w>h
" hit esc for Normal mode in terminal
tmap <Esc> <C-\><C-n>


" Coc
set encoding=utf-8
" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup
set updatetime=300
"set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" fzf
let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name ''*.tags'' -printf ''%P\n'''
nnoremap <C-p> :Files<Cr>
nnoremap <C-b> :Buffers<Cr>
nnoremap <C-g> :GFiles<Cr>
nnoremap <leader>c :Commits<Cr>

