env:
    TERM: xterm-256color

scrolling:
    history: 5000

window:
  # Window dimensions (changes require restart)
  #
  # Number of lines/columns (not pixels) in the terminal. The number of columns
  # must be at least `2`, while using a value of `0` for columns and lines will
  # fall back to the window manager's recommended size.
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

    opacity: 1.0


colors:
  # Colors (Gruvbox Material Dark Medium)
  # Default colors
  Primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  selection:
    text: '0xf8f8f2'
    background: '0x44475a'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []

font:
  normal:
    family: Terminus
    style: Bold

  bold:
    family: Terminus
    style: Bold

  italic:
    family: Terminus
    style: Italic

  bold_italic:
    family: Terminus
    style: Bold Italic

  size: 16


# Key bindings
Key_bindings:
    - { key: Equals,   mods: Super, action: IncreaseFontSize }
    - { Key: Subtract, mods: Super, action: DecreaseFontSize }
    - { key: Key0,     mods: Super, action: ResetFontSize    }
    - { key: PageUp,   mods: Shift,   action: ScrollPageUp   }
    - { key: PageDown, mods: Shift,   action: ScrollPageDown }
    - { key: End,      mods: Shift,   action: ScrollToBottom }
    - { key: Home,     mods: Shift,   action: ScrollToTop    }
    - { key: V,        mods: Control|Alt,  action: Paste       }
    - { key: C,        mods: Control|Alt,  action: Copy        }
    - { key: Return,   mods: Control, action: SpawnNewInstance }
    - { key: T,        mods: Control, action: SpawnNewInstance }
